// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// CreateDocumentBadRequest is response for CreateDocument operation.
type CreateDocumentBadRequest struct{}

func (*CreateDocumentBadRequest) createDocumentRes() {}

// CreateDocumentInternalServerError is response for CreateDocument operation.
type CreateDocumentInternalServerError struct{}

func (*CreateDocumentInternalServerError) createDocumentRes() {}

// DeleteDocumentByNumberBadRequest is response for DeleteDocumentByNumber operation.
type DeleteDocumentByNumberBadRequest struct{}

func (*DeleteDocumentByNumberBadRequest) deleteDocumentByNumberRes() {}

// DeleteDocumentByNumberInternalServerError is response for DeleteDocumentByNumber operation.
type DeleteDocumentByNumberInternalServerError struct{}

func (*DeleteDocumentByNumberInternalServerError) deleteDocumentByNumberRes() {}

// DeleteDocumentByNumberNoContent is response for DeleteDocumentByNumber operation.
type DeleteDocumentByNumberNoContent struct{}

func (*DeleteDocumentByNumberNoContent) deleteDocumentByNumberRes() {}

// DeleteDocumentByNumberNotFound is response for DeleteDocumentByNumber operation.
type DeleteDocumentByNumberNotFound struct{}

func (*DeleteDocumentByNumberNotFound) deleteDocumentByNumberRes() {}

// Ref: #/components/schemas/DocumentCreateRequest
type DocumentCreateRequest struct {
	UserID         int64      `json:"user_id"`
	DocumentType   string     `json:"document_type"`
	DocumentNumber string     `json:"document_number"`
	DateCreated    time.Time  `json:"date_created"`
	DateEnd        OptNilDate `json:"date_end"`
	Persons        []Person   `json:"persons"`
}

// GetUserID returns the value of UserID.
func (s *DocumentCreateRequest) GetUserID() int64 {
	return s.UserID
}

// GetDocumentType returns the value of DocumentType.
func (s *DocumentCreateRequest) GetDocumentType() string {
	return s.DocumentType
}

// GetDocumentNumber returns the value of DocumentNumber.
func (s *DocumentCreateRequest) GetDocumentNumber() string {
	return s.DocumentNumber
}

// GetDateCreated returns the value of DateCreated.
func (s *DocumentCreateRequest) GetDateCreated() time.Time {
	return s.DateCreated
}

// GetDateEnd returns the value of DateEnd.
func (s *DocumentCreateRequest) GetDateEnd() OptNilDate {
	return s.DateEnd
}

// GetPersons returns the value of Persons.
func (s *DocumentCreateRequest) GetPersons() []Person {
	return s.Persons
}

// SetUserID sets the value of UserID.
func (s *DocumentCreateRequest) SetUserID(val int64) {
	s.UserID = val
}

// SetDocumentType sets the value of DocumentType.
func (s *DocumentCreateRequest) SetDocumentType(val string) {
	s.DocumentType = val
}

// SetDocumentNumber sets the value of DocumentNumber.
func (s *DocumentCreateRequest) SetDocumentNumber(val string) {
	s.DocumentNumber = val
}

// SetDateCreated sets the value of DateCreated.
func (s *DocumentCreateRequest) SetDateCreated(val time.Time) {
	s.DateCreated = val
}

// SetDateEnd sets the value of DateEnd.
func (s *DocumentCreateRequest) SetDateEnd(val OptNilDate) {
	s.DateEnd = val
}

// SetPersons sets the value of Persons.
func (s *DocumentCreateRequest) SetPersons(val []Person) {
	s.Persons = val
}

// Ref: #/components/schemas/DocumentResponse
type DocumentResponse struct {
	UserID         int64      `json:"user_id"`
	DocumentType   string     `json:"document_type"`
	DocumentNumber string     `json:"document_number"`
	DateCreated    time.Time  `json:"date_created"`
	DateEnd        OptNilDate `json:"date_end"`
	Persons        []Person   `json:"persons"`
}

// GetUserID returns the value of UserID.
func (s *DocumentResponse) GetUserID() int64 {
	return s.UserID
}

// GetDocumentType returns the value of DocumentType.
func (s *DocumentResponse) GetDocumentType() string {
	return s.DocumentType
}

// GetDocumentNumber returns the value of DocumentNumber.
func (s *DocumentResponse) GetDocumentNumber() string {
	return s.DocumentNumber
}

// GetDateCreated returns the value of DateCreated.
func (s *DocumentResponse) GetDateCreated() time.Time {
	return s.DateCreated
}

// GetDateEnd returns the value of DateEnd.
func (s *DocumentResponse) GetDateEnd() OptNilDate {
	return s.DateEnd
}

// GetPersons returns the value of Persons.
func (s *DocumentResponse) GetPersons() []Person {
	return s.Persons
}

// SetUserID sets the value of UserID.
func (s *DocumentResponse) SetUserID(val int64) {
	s.UserID = val
}

// SetDocumentType sets the value of DocumentType.
func (s *DocumentResponse) SetDocumentType(val string) {
	s.DocumentType = val
}

// SetDocumentNumber sets the value of DocumentNumber.
func (s *DocumentResponse) SetDocumentNumber(val string) {
	s.DocumentNumber = val
}

// SetDateCreated sets the value of DateCreated.
func (s *DocumentResponse) SetDateCreated(val time.Time) {
	s.DateCreated = val
}

// SetDateEnd sets the value of DateEnd.
func (s *DocumentResponse) SetDateEnd(val OptNilDate) {
	s.DateEnd = val
}

// SetPersons sets the value of Persons.
func (s *DocumentResponse) SetPersons(val []Person) {
	s.Persons = val
}

func (*DocumentResponse) createDocumentRes()  {}
func (*DocumentResponse) getDocumentByIDRes() {}

// GetDocumentByIDInternalServerError is response for GetDocumentByID operation.
type GetDocumentByIDInternalServerError struct{}

func (*GetDocumentByIDInternalServerError) getDocumentByIDRes() {}

// GetDocumentByIDNotFound is response for GetDocumentByID operation.
type GetDocumentByIDNotFound struct{}

func (*GetDocumentByIDNotFound) getDocumentByIDRes() {}

// Ref: #/components/schemas/LegalEntity
type LegalEntity struct {
	Name       string    `json:"name"`
	EntityType OptString `json:"entity_type"`
}

// GetName returns the value of Name.
func (s *LegalEntity) GetName() string {
	return s.Name
}

// GetEntityType returns the value of EntityType.
func (s *LegalEntity) GetEntityType() OptString {
	return s.EntityType
}

// SetName sets the value of Name.
func (s *LegalEntity) SetName(val string) {
	s.Name = val
}

// SetEntityType sets the value of EntityType.
func (s *LegalEntity) SetEntityType(val OptString) {
	s.EntityType = val
}

// ListDocumentsBadRequest is response for ListDocuments operation.
type ListDocumentsBadRequest struct{}

func (*ListDocumentsBadRequest) listDocumentsRes() {}

// ListDocumentsInternalServerError is response for ListDocuments operation.
type ListDocumentsInternalServerError struct{}

func (*ListDocumentsInternalServerError) listDocumentsRes() {}

type ListDocumentsOK struct {
	Total     int                `json:"total"`
	Documents []DocumentResponse `json:"documents"`
}

// GetTotal returns the value of Total.
func (s *ListDocumentsOK) GetTotal() int {
	return s.Total
}

// GetDocuments returns the value of Documents.
func (s *ListDocumentsOK) GetDocuments() []DocumentResponse {
	return s.Documents
}

// SetTotal sets the value of Total.
func (s *ListDocumentsOK) SetTotal(val int) {
	s.Total = val
}

// SetDocuments sets the value of Documents.
func (s *ListDocumentsOK) SetDocuments(val []DocumentResponse) {
	s.Documents = val
}

func (*ListDocumentsOK) listDocumentsRes() {}

// Ref: #/components/schemas/NaturalPerson
type NaturalPerson struct {
	FirstName  OptNilString `json:"first_name"`
	LastName   OptNilString `json:"last_name"`
	MiddleName OptNilString `json:"middle_name"`
	Initials   OptNilString `json:"initials"`
}

// GetFirstName returns the value of FirstName.
func (s *NaturalPerson) GetFirstName() OptNilString {
	return s.FirstName
}

// GetLastName returns the value of LastName.
func (s *NaturalPerson) GetLastName() OptNilString {
	return s.LastName
}

// GetMiddleName returns the value of MiddleName.
func (s *NaturalPerson) GetMiddleName() OptNilString {
	return s.MiddleName
}

// GetInitials returns the value of Initials.
func (s *NaturalPerson) GetInitials() OptNilString {
	return s.Initials
}

// SetFirstName sets the value of FirstName.
func (s *NaturalPerson) SetFirstName(val OptNilString) {
	s.FirstName = val
}

// SetLastName sets the value of LastName.
func (s *NaturalPerson) SetLastName(val OptNilString) {
	s.LastName = val
}

// SetMiddleName sets the value of MiddleName.
func (s *NaturalPerson) SetMiddleName(val OptNilString) {
	s.MiddleName = val
}

// SetInitials sets the value of Initials.
func (s *NaturalPerson) SetInitials(val OptNilString) {
	s.Initials = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLegalEntity returns new OptLegalEntity with value set to v.
func NewOptLegalEntity(v LegalEntity) OptLegalEntity {
	return OptLegalEntity{
		Value: v,
		Set:   true,
	}
}

// OptLegalEntity is optional LegalEntity.
type OptLegalEntity struct {
	Value LegalEntity
	Set   bool
}

// IsSet returns true if OptLegalEntity was set.
func (o OptLegalEntity) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLegalEntity) Reset() {
	var v LegalEntity
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLegalEntity) SetTo(v LegalEntity) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLegalEntity) Get() (v LegalEntity, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLegalEntity) Or(d LegalEntity) LegalEntity {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNaturalPerson returns new OptNaturalPerson with value set to v.
func NewOptNaturalPerson(v NaturalPerson) OptNaturalPerson {
	return OptNaturalPerson{
		Value: v,
		Set:   true,
	}
}

// OptNaturalPerson is optional NaturalPerson.
type OptNaturalPerson struct {
	Value NaturalPerson
	Set   bool
}

// IsSet returns true if OptNaturalPerson was set.
func (o OptNaturalPerson) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNaturalPerson) Reset() {
	var v NaturalPerson
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNaturalPerson) SetTo(v NaturalPerson) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNaturalPerson) Get() (v NaturalPerson, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNaturalPerson) Or(d NaturalPerson) NaturalPerson {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDate returns new OptNilDate with value set to v.
func NewOptNilDate(v time.Time) OptNilDate {
	return OptNilDate{
		Value: v,
		Set:   true,
	}
}

// OptNilDate is optional nullable time.Time.
type OptNilDate struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDate was set.
func (o OptNilDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDate) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDate) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDate) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDate) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Person
type Person struct {
	Type          PersonType       `json:"type"`
	LegalEntity   OptLegalEntity   `json:"legal_entity"`
	NaturalPerson OptNaturalPerson `json:"natural_person"`
}

// GetType returns the value of Type.
func (s *Person) GetType() PersonType {
	return s.Type
}

// GetLegalEntity returns the value of LegalEntity.
func (s *Person) GetLegalEntity() OptLegalEntity {
	return s.LegalEntity
}

// GetNaturalPerson returns the value of NaturalPerson.
func (s *Person) GetNaturalPerson() OptNaturalPerson {
	return s.NaturalPerson
}

// SetType sets the value of Type.
func (s *Person) SetType(val PersonType) {
	s.Type = val
}

// SetLegalEntity sets the value of LegalEntity.
func (s *Person) SetLegalEntity(val OptLegalEntity) {
	s.LegalEntity = val
}

// SetNaturalPerson sets the value of NaturalPerson.
func (s *Person) SetNaturalPerson(val OptNaturalPerson) {
	s.NaturalPerson = val
}

type PersonType string

const (
	PersonTypeLEGALENTITY   PersonType = "LEGAL_ENTITY"
	PersonTypeNATURALPERSON PersonType = "NATURAL_PERSON"
)

// AllValues returns all PersonType values.
func (PersonType) AllValues() []PersonType {
	return []PersonType{
		PersonTypeLEGALENTITY,
		PersonTypeNATURALPERSON,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PersonType) MarshalText() ([]byte, error) {
	switch s {
	case PersonTypeLEGALENTITY:
		return []byte(s), nil
	case PersonTypeNATURALPERSON:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PersonType) UnmarshalText(data []byte) error {
	switch PersonType(data) {
	case PersonTypeLEGALENTITY:
		*s = PersonTypeLEGALENTITY
		return nil
	case PersonTypeNATURALPERSON:
		*s = PersonTypeNATURALPERSON
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
