// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateDocument implements createDocument operation.
	//
	// Save parsed document.
	//
	// POST /documents
	CreateDocument(ctx context.Context, req *DocumentCreateRequest) (CreateDocumentRes, error)
	// DeleteDocumentByNumber implements deleteDocumentByNumber operation.
	//
	// Delete document by number.
	//
	// DELETE /documents/by-number/{document_number}
	DeleteDocumentByNumber(ctx context.Context, params DeleteDocumentByNumberParams) (DeleteDocumentByNumberRes, error)
	// GetDocumentByID implements getDocumentByID operation.
	//
	// Get document by ID.
	//
	// GET /documents/{id}
	GetDocumentByID(ctx context.Context, params GetDocumentByIDParams) (GetDocumentByIDRes, error)
	// ListDocuments implements listDocuments operation.
	//
	// Get user documents.
	//
	// GET /documents
	ListDocuments(ctx context.Context, params ListDocumentsParams) (ListDocumentsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
