// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateDocumentOperation         OperationName = "CreateDocument"
	DeleteDocumentByNumberOperation OperationName = "DeleteDocumentByNumber"
	GetDocumentByIDOperation        OperationName = "GetDocumentByID"
	ListDocumentsOperation          OperationName = "ListDocuments"
)
