// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateDocument implements createDocument operation.
//
// Save parsed document.
//
// POST /documents
func (UnimplementedHandler) CreateDocument(ctx context.Context, req *DocumentCreateRequest) (r CreateDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDocumentByNumber implements deleteDocumentByNumber operation.
//
// Delete document by number.
//
// DELETE /documents/by-number/{document_number}
func (UnimplementedHandler) DeleteDocumentByNumber(ctx context.Context, params DeleteDocumentByNumberParams) (r DeleteDocumentByNumberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocumentByID implements getDocumentByID operation.
//
// Get document by ID.
//
// GET /documents/{id}
func (UnimplementedHandler) GetDocumentByID(ctx context.Context, params GetDocumentByIDParams) (r GetDocumentByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDocuments implements listDocuments operation.
//
// Get user documents.
//
// GET /documents
func (UnimplementedHandler) ListDocuments(ctx context.Context, params ListDocumentsParams) (r ListDocumentsRes, _ error) {
	return r, ht.ErrNotImplemented
}
