// Code generated by ogen, DO NOT EDIT.
package api

type CreateDocumentRes interface {
	createDocumentRes()
}

type DeleteDocumentByNumberRes interface {
	deleteDocumentByNumberRes()
}

type GetDocumentByIDRes interface {
	getDocumentByIDRes()
}

type ListDocumentsRes interface {
	listDocumentsRes()
}
